pd = "http-file-browser"
interface_types = "0.1.0"
description = "HTTP file browser over FS + net TCP listen IPC"

[fragment]
pds = ["http-file-browser"]
requires = ["fs-server", "net-server"]

[[fragment.channel]]
name = "http_fs_net"
ends = [
  { pd = "net_server", id = 7 },
  { pd = "http_file_browser", id = 0, pp = true },
]

[[fragment.channel]]
name = "http_fs_fs"
ends = [
  { pd = "fs_server", id = 7 },
  { pd = "http_file_browser", id = 1, pp = true },
]
