//! The system-call ABI, shared between the kernel and userspace (inlined as
//! `lerux-syscall`).
//!
//! This crate is the *contract* both sides of a syscall agree on: the call
//! numbers ([`number`]), the flags ([`flag`]), the error codes ([`error`]), and
//! the data structures passed by pointer ([`data`]). The kernel reads these
//! definitions to decode incoming calls; the userspace runtime uses the same
//! definitions to make them. Because both sides are compiled from this one
//! source, they cannot drift out of sync.
//!
//! ## Why it is inlined
//!
//! Upstream this is the external `redox_syscall` crate. lerux copies it into the
//! tree (wired in as `__redox_syscall` via `#[path]` in `main.rs`, then
//! re-exported as `syscall`) to keep zero external runtime dependencies. It is
//! effectively part of the kernel's stable interface.
//!
//! The `arch/` submodule selects the per-architecture pieces (register layout,
//! the trap instruction wrapper). The `userspace` feature gates [`call`], the
//! thin wrappers a userspace program calls to actually issue syscalls — the
//! kernel build does not need those.
//!
//! See also: [`docs/kernel/architecture.md`] section 6 ("System calls").
//!
//! [`docs/kernel/architecture.md`]: ../../../../docs/kernel/architecture.md

#[cfg(test)]
extern crate core;

pub use self::{arch::*, data::*, error::*, flag::*, io::*, number::*};

#[cfg(target_arch = "aarch64")]
#[path = "arch/aarch64.rs"]
mod arch;

#[cfg(target_arch = "riscv64")]
#[path = "arch/riscv64.rs"]
mod arch;

#[cfg(target_arch = "x86")]
#[path = "arch/x86.rs"]
mod arch;

#[cfg(target_arch = "x86_64")]
#[path = "arch/x86_64.rs"]
mod arch;

/// Function definitions
#[cfg(feature = "userspace")]
pub mod call;

#[cfg(feature = "userspace")]
pub use call::*;

/// Complex structures that are used for some system calls
pub mod data;

pub mod dirent;

/// All errors that can be generated by a system call
pub mod error;

/// Flags used as an argument to many system calls
pub mod flag;

/// Functions for low level hardware control
pub mod io;

/// Call numbers used by each system call
pub mod number;

/// ABI for shared memory based signals
pub mod sigabi;

/// V2 scheme format
pub mod schemev2;
