[package]
name = "program-runtime"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Untrusted PD that fetches a signed Wasm module and runs it"

[lints]
workspace = true

[features]
board-qemu_virt_aarch64_program = []

[dependencies]
lerux-interface-types = { path = "../../crates/lerux-interface-types" }
lerux-ipc = { path = "../../crates/lerux-ipc" }
lerux-logging = { path = "../../crates/lerux-logging", features = ["serial"] }
lerux-prog = { path = "../../crates/lerux-prog" }
sel4-microkit = { workspace = true, features = ["alloc"] }
