//! Emit and check Rust `Channel` constants against a profile manifest (Phase 41).
//!
//! The structured `[[channel]]` list is the source of truth. PD crates still
//! hard-code `Channel::new(N)`; `check_profile_channels` catches drift, and
//! `emit_channel_consts_rs` produces a reference module for humans/agents.

use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

use anyhow::{bail, Context, Result};
use regex::Regex;

use crate::{
    channels::{to_sdf_pd_name, ChannelSpec},
    profile::Profile,
};

/// Local channel ids used by each SDF PD name, derived from the manifest.
pub fn pd_local_ids(channels: &[ChannelSpec]) -> BTreeMap<String, BTreeSet<u8>> {
    let mut map: BTreeMap<String, BTreeSet<u8>> = BTreeMap::new();
    for ch in channels {
        for end in &ch.ends {
            map.entry(to_sdf_pd_name(&end.pd))
                .or_default()
                .insert(end.id);
        }
    }
    map
}

/// Peer edges: for each PD, map local id → peer SDF name.
pub fn pd_peer_map(channels: &[ChannelSpec]) -> BTreeMap<String, BTreeMap<u8, String>> {
    let mut map: BTreeMap<String, BTreeMap<u8, String>> = BTreeMap::new();
    for ch in channels {
        if ch.ends.len() != 2 {
            continue;
        }
        let a = &ch.ends[0];
        let b = &ch.ends[1];
        let a_pd = to_sdf_pd_name(&a.pd);
        let b_pd = to_sdf_pd_name(&b.pd);
        map.entry(a_pd.clone())
            .or_default()
            .insert(a.id, b_pd.clone());
        map.entry(b_pd).or_default().insert(b.id, a_pd);
    }
    map
}

/// Generate a Rust module listing each PD's channel ids and peers.
pub fn emit_channel_consts_rs(profile_name: &str, channels: &[ChannelSpec]) -> String {
    let peers = pd_peer_map(channels);
    let mut out = String::new();
    out.push_str("// @generated by `lerux profile emit-channels` — do not hand-edit.\n");
    out.push_str(&format!(
        "// Profile: {profile_name}\n// Source: support/profiles/{profile_name}.toml [[channel]]\n\n"
    ));
    out.push_str("#![allow(dead_code)]\n\n");
    out.push_str("//! Channel ids from the system profile manifest (Phase 41).\n");
    out.push_str("//! PD crates should keep `const …: Channel = Channel::new(N)` in sync;\n");
    out.push_str("//! run `lerux profile check-channels` to verify.\n\n");

    for (pd, id_map) in &peers {
        out.push_str(&format!("pub mod {pd} {{\n"));
        out.push_str("    //! Local Microkit channel ids for this protection domain.\n");
        for (id, peer) in id_map {
            let const_name = peer.to_uppercase();
            out.push_str(&format!("    /// IPC to `{peer}` (SDF channel id {id}).\n"));
            out.push_str(&format!("    pub const {const_name}: u8 = {id};\n"));
        }
        out.push_str("}\n\n");
    }
    out
}

/// Parse all `Channel::new(N)` integer literals from Rust source.
#[cfg(test)]
pub fn parse_channel_new_ids(source: &str) -> BTreeSet<u8> {
    let re = Regex::new(r"Channel::new\s*\(\s*(\d+)\s*\)").expect("channel new regex");
    re.captures_iter(source)
        .filter_map(|c| c.get(1)?.as_str().parse::<u8>().ok())
        .collect()
}

/// Parse `const NAME: Channel = Channel::new(N)` bindings.
pub fn parse_named_channel_consts(source: &str) -> Vec<(String, u8)> {
    let re =
        Regex::new(r"const\s+([A-Z][A-Z0-9_]*)\s*:\s*Channel\s*=\s*Channel::new\s*\(\s*(\d+)\s*\)")
            .expect("named channel const regex");
    re.captures_iter(source)
        .filter_map(|c| {
            let name = c.get(1)?.as_str().to_string();
            let id = c.get(2)?.as_str().parse::<u8>().ok()?;
            Some((name, id))
        })
        .collect()
}

fn crate_dir_for_pd(root: &Path, pd_crate: &str) -> PathBuf {
    root.join("userspace/pds").join(pd_crate)
}

fn collect_rs_sources(dir: &Path) -> Result<String> {
    let mut combined = String::new();
    if !dir.is_dir() {
        return Ok(combined);
    }
    fn walk(dir: &Path, out: &mut String) -> Result<()> {
        for entry in fs::read_dir(dir).with_context(|| format!("read {}", dir.display()))? {
            let entry = entry?;
            let path = entry.path();
            if path.is_dir() {
                walk(&path, out)?;
            } else if path.extension().and_then(|e| e.to_str()) == Some("rs") {
                let text = fs::read_to_string(&path)
                    .with_context(|| format!("read {}", path.display()))?;
                out.push_str(&text);
                out.push('\n');
            }
        }
        Ok(())
    }
    walk(dir, &mut combined)?;
    Ok(combined)
}

/// Check that named `const …: Channel = Channel::new(N)` bindings in each
/// profile PD match the manifest when the named peer is present in this profile.
///
/// Consts for peers that do not appear in the profile (e.g. PL031 on RPi4) are
/// ignored — they are expected to be behind `#[cfg]` in source.
pub fn check_profile_channels(root: &Path, profile_name: &str, profile: &Profile) -> Result<()> {
    let peers = pd_peer_map(&profile.channel);
    let local_ids = pd_local_ids(&profile.channel);
    let mut errors: Vec<String> = Vec::new();

    for pd_crate in &profile.pds {
        let sdf = to_sdf_pd_name(pd_crate);
        let Some(peer_map) = peers.get(&sdf) else {
            continue;
        };
        let Some(_allowed) = local_ids.get(&sdf) else {
            continue;
        };
        let dir = crate_dir_for_pd(root, pd_crate);
        if !dir.is_dir() {
            errors.push(format!("PD crate directory missing: {}", dir.display()));
            continue;
        }
        let source = collect_rs_sources(&dir)?;
        if source.is_empty() {
            continue;
        }

        let peers_present: BTreeSet<&str> = peer_map.values().map(String::as_str).collect();

        // Group by const name — PDs often have cfg-gated Channel::new aliases.
        let mut by_name: BTreeMap<String, BTreeSet<u8>> = BTreeMap::new();
        for (const_name, id) in parse_named_channel_consts(&source) {
            by_name.entry(const_name).or_default().insert(id);
        }

        for (const_name, ids) in &by_name {
            let Some(expected_peer) = const_name_to_peer_sdf(const_name) else {
                continue;
            };
            let peer_in_profile = peers_present
                .iter()
                .any(|p| *p == expected_peer.as_str() || peer_aliases(p, &expected_peer));
            if !peer_in_profile {
                continue;
            }
            let expected_ids: BTreeSet<u8> = peer_map
                .iter()
                .filter(|(_, peer)| *peer == &expected_peer || peer_aliases(peer, &expected_peer))
                .map(|(id, _)| *id)
                .collect();
            if expected_ids.is_empty() {
                continue;
            }
            // Pass if any cfg-gated binding matches the manifest id.
            if ids.is_disjoint(&expected_ids) {
                errors.push(format!(
                    "{pd_crate}: const {const_name} uses Channel::new ids {ids:?}, \
                     but manifest requires one of {expected_ids:?} for peer {expected_peer}"
                ));
            }
        }
    }

    if !errors.is_empty() {
        bail!(
            "profile {profile_name} channel check failed ({} issue(s)):\n  - {}",
            errors.len(),
            errors.join("\n  - ")
        );
    }
    Ok(())
}

/// Map a Rust const name to an expected peer SDF name when unambiguous.
fn const_name_to_peer_sdf(name: &str) -> Option<String> {
    let n = name.to_uppercase();
    let peer = match n.as_str() {
        "SERIAL_DRIVER" => "serial_driver",
        "FS_SERVER" => "fs_server",
        "NET_SERVER" => "net_server",
        "LOG_SERVER" => "log_server",
        "CONFIG_SERVER" => "config_server",
        "SUPERVISOR" | "BOOT_INIT" => "supervisor",
        "SHELL" => "shell",
        "EDIT" => "edit",
        "CHAT" | "CHAT_CLIENT" => "chat_client",
        "HTTP_FS_CLIENT" | "HTTP_FILE_BROWSER" => "http_file_browser",
        "ECHO_SERVER" => "echo_server",
        "ECHO_CLIENT" => "echo_client",
        "PL031_DRIVER" | "RTC_DRIVER" => "pl031_driver",
        "SP804_DRIVER" | "TIMER_DRIVER" => "sp804_driver",
        "VIRTIO_BLK_DRIVER" | "BLK_DRIVER" => "virtio_blk_driver",
        "VIRTIO_NET_DRIVER" | "NET_DRIVER" => "virtio_net_driver",
        "GENET_DRIVER" => "genet_driver",
        "EMMC2_DRIVER" => "emmc2_driver",
        "CLIENT" | "DEVICE" | "APP" | "CLIENTS" => return None,
        _ => return None,
    };
    Some(peer.into())
}

fn peer_aliases(actual: &str, expected: &str) -> bool {
    matches!(
        (actual, expected),
        ("emmc2_driver", "virtio_blk_driver")
            | ("virtio_blk_driver", "emmc2_driver")
            | ("genet_driver", "virtio_net_driver")
            | ("virtio_net_driver", "genet_driver")
            // Phase 42: clients still name SERIAL_DRIVER but peer is serial_virt.
            | ("serial_virt", "serial_driver")
            | ("serial_driver", "serial_virt")
    )
}

/// Write generated channel const module next to a system build output.
pub fn write_channel_consts(
    root: &Path,
    board: &str,
    build_dir: &str,
    profile_name: &str,
    profile: &Profile,
) -> Result<PathBuf> {
    let path = root.join(build_dir).join(board).join("channel_consts.rs");
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("mkdir {}", parent.display()))?;
    }
    let body = emit_channel_consts_rs(profile_name, &profile.channel);
    fs::write(&path, body).with_context(|| format!("write {}", path.display()))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::channels::{ChannelEnd, ChannelSpec};

    fn ch(a_pd: &str, a_id: u8, b_pd: &str, b_id: u8) -> ChannelSpec {
        ChannelSpec {
            name: None,
            ends: vec![
                ChannelEnd {
                    pd: a_pd.into(),
                    id: a_id,
                    pp: false,
                },
                ChannelEnd {
                    pd: b_pd.into(),
                    id: b_id,
                    pp: true,
                },
            ],
        }
    }

    #[test]
    fn parse_channel_news() {
        let src = "const X: Channel = Channel::new(3);\n foo(Channel::new(7));";
        assert_eq!(parse_channel_new_ids(src), BTreeSet::from([3, 7]));
        assert_eq!(parse_named_channel_consts(src), vec![("X".into(), 3)]);
    }

    #[test]
    fn emit_contains_modules() {
        let channels = vec![ch("serial_driver", 1, "shell", 0)];
        let rs = emit_channel_consts_rs("minimal", &channels);
        assert!(rs.contains("pub mod shell"));
        assert!(rs.contains("pub const SERIAL_DRIVER: u8 = 0"));
        assert!(rs.contains("pub mod serial_driver"));
        assert!(rs.contains("pub const SHELL: u8 = 1"));
    }

    #[test]
    fn workstation_check_passes() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let profiles = crate::profile::load_profiles(&root).unwrap();
        let p = profiles.get("workstation").unwrap();
        check_profile_channels(&root, "workstation", p).expect("workstation channels ok");
    }

    #[test]
    fn workstation_rpi4_check_passes() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let profiles = crate::profile::load_profiles(&root).unwrap();
        let p = profiles.get("workstation-rpi4").unwrap();
        check_profile_channels(&root, "workstation-rpi4", p).expect("rpi4 channels ok");
    }
}
